//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiliCookoff2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chili
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Number { get; set; }
        public System.Guid ChefId { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public int Votes { get; set; }
        public Nullable<int> Place { get; set; }
        public System.Guid PartyId { get; set; }
    }
}
