//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiliCookoff2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChiliCookoffEntities : DbContext
    {
        public ChiliCookoffEntities()
            : base("name=ChiliCookoffEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Ballot> Ballots { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Chef> Chefs { get; set; }
        public virtual DbSet<Chili> Chilis { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<PartyPerson> PartyPersons { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<Voter> Voters { get; set; }
        public virtual DbSet<ChiliNumberControl> ChiliNumberControls { get; set; }
    }
}
