//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiliCookoff2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public System.Guid Id { get; set; }
        public System.Guid HostId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool HasVotingStarted { get; set; }
        public bool HaveVotesBeenTallied { get; set; }
        public int MaxChilis { get; set; }
    }
}
