//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChiliCookoff2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public System.Guid Id { get; set; }
        public System.Guid BallotId { get; set; }
        public System.Guid ChiliId { get; set; }
        public int Points { get; set; }
        public string Comments { get; set; }
    }
}
